### ISSUE TITLE
Blank page while build in store

### ISSUE THREAD

**Issue by Harish-kannan2** [spurtcommerce/spurtcommerce#14]
Hi , after build of store i am seeing only blank page. In browser console following error is coming

agm-core.js:4538 Uncaught TypeError: Object(...) is not a function
at agm-core.js:4538
at Module../node_modules/@agm/core/fesm5/agm-core.js (agm-core.js:4544)
at webpack_require (bootstrap:83)
at Module../src/default/shared/components/index.ts (header.component.ts:17)
at webpack_require (bootstrap:83)
at Module../src/default/default.module.ts (default.component.ts:23)
at webpack_require (bootstrap:83)
at Module../src/main.ts (main.ts:1)
at webpack_require (bootstrap:83)
at Object.0 (main.ts:22)
client:148 [WDS] Warnings while compiling.
warnings @ client:148
client:154 ./node_modules/@agm/core/fesm5/agm-core.js 4538:34-52
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
client:154 ./node_modules/@agm/core/fesm5/agm-core.js 4538:120-128
"export 'ɵɵinject' was not found in '@angular/core'

ng --version info is as below:

Angular CLI: 7.0.6
Node: 10.16.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package Version
@angular-devkit/architect 0.10.6
@angular-devkit/build-angular 0.10.6
@angular-devkit/build-optimizer 0.10.6
@angular-devkit/build-webpack 0.10.6
@angular-devkit/core 7.0.6
@angular-devkit/schematics 7.0.6
@angular/cdk 7.3.7
@angular/cli 7.0.6
@angular/flex-layout 7.0.0-beta.19
@angular/platform-server 7.2.16
@ngtools/webpack 7.0.6
@schematics/angular 7.0.6
@schematics/update 0.10.6
rxjs 6.3.3
typescript 3.1.6
webpack 4.19.1

**Comment by Piccoserver** [comment]
Try this `npm i @agm/core@1.0.0-beta.3 --save`
