### ISSUE TITLE
No frontend/stores folder [Closed]

### ISSUE THREAD

**Issue by adiwastu** [spurtcommerce/spurtcommerce#87]
I'm following the tutorial to build the site, everything launches nicely, except there's no stores folder, only admin and vendor. May I know where to get those? Also, how can I add users than can log in into the admin panel? thank you!

Hotland

**Comment by spurtcomm** [comment]
Hi, Please check here https://github.com/spurtcommerce/spurtcommerce/tree/master/frontend

**Comment by spurtcomm** [comment]
Hi, Please check here https://github.com/spurtcommerce/spurtcommerce/tree/master/frontend

**Comment by rusaik** [comment]
Seller is not available in the link provided, Can you please assist on this ?

> Hi, Please check here https://github.com/spurtcommerce/spurtcommerce/tree/master/frontend
